# Generated by Django 5.1.5 on 2025-02-06 09:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Competencies',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('recruiter', 'Recruiter'), ('technical', 'Technical Interviewer'), ('hr', 'HR Manager'), ('manager', 'Hiring Manager')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='core.client')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('client', 'key')},
            },
        ),
        migrations.CreateModel(
            name='PipelineSubStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_statuses', to='core.pipelinestage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('stage', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Active'), ('closed', 'Closed'), ('hold', 'On Hold')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('resume', models.FileField(blank=True, help_text='Allowed formats: PDF, DOC, DOCX', null=True, upload_to='resumes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('status', models.CharField(choices=[('new', 'New'), ('screening', 'Screening'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competencies', models.ManyToManyField(blank=True, to='core.competency')),
                ('languages', models.ManyToManyField(blank=True, to='core.language')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='core.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pipelinestage')),
                ('sub_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pipelinesubstatus')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='candidates',
            field=models.ManyToManyField(related_name='positions', through='core.RecruitingProcess', to='core.candidate'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('phone_screen', 'Phone Screen'), ('technical', 'Technical Interview'), ('hr', 'HR Interview'), ('client', 'Client Interview'), ('final', 'Final Interview')], max_length=20)),
                ('date_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recruiter')),
                ('recruiting_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.recruitingprocess')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.recruitingprocess')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RejectionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('email_subject', models.CharField(default='Application Status Update', max_length=200)),
                ('email_body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recruiting_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recruitingprocess')),
            ],
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('new_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_status_changes', to='core.pipelinestage')),
                ('new_sub_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_status_changes', to='core.pipelinesubstatus')),
                ('old_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_status_changes', to='core.pipelinestage')),
                ('old_sub_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_status_changes', to='core.pipelinesubstatus')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='core.recruitingprocess')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
