# Generated by Django 5.1.5 on 2025-02-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Jobs', 'Jobs'), ('Internal', 'Internal')], default='LinkedIn', max_length=20),
        ),
        migrations.AddField(
            model_name='recruitingprocess',
            name='cv_match',
            field=models.IntegerField(blank=True, help_text='CV match percentage', null=True),
        ),
        migrations.AddField(
            model_name='recruitingprocess',
            name='interview_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Interview score out of 10', max_digits=3, null=True),
        ),
    ]
