# Generated by Django 5.1.5 on 2025-02-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('clients', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='clients.client')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('client', 'key')},
            },
        ),
        migrations.CreateModel(
            name='PipelineSubStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_statuses', to='recruitment.pipelinestage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('stage', 'key')},
            },
        ),
        migrations.CreateModel(
            name='RecruitingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_score', models.DecimalField(blank=True, decimal_places=1, help_text='Interview score out of 10', max_digits=3, null=True)),
                ('cv_match', models.IntegerField(blank=True, help_text='CV match percentage', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='positions.position')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.pipelinestage')),
                ('sub_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.pipelinesubstatus')),
            ],
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('new_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_status_changes', to='recruitment.pipelinestage')),
                ('new_sub_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_status_changes', to='recruitment.pipelinesubstatus')),
                ('old_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_status_changes', to='recruitment.pipelinestage')),
                ('old_sub_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_status_changes', to='recruitment.pipelinesubstatus')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='recruitment.recruitingprocess')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
