# Generated by Django 5.1.5 on 2025-02-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('clients', '0001_initial'),
        ('positions', '0001_initial'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='candidates',
            field=models.ManyToManyField(related_name='positions', through='recruitment.RecruitingProcess', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='position',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='clients.client'),
        ),
    ]
