from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('candidates/', views.candidate_list, name='candidate_list'),
    path('search/', views.advanced_search, name='advanced_search'),
    path('positions/', views.position_list, name='position_list'),
    path('clients/', views.client_list, name='client_list'),
    path('clients/add/', views.add_client, name='add_client'),
    path('clients/<int:client_id>/edit/', views.edit_client, name='edit_client'),
    path('clients/<int:client_id>/delete/', views.delete_client, name='delete_client'),
    path('positions/add/', views.add_position, name='add_position'),
    path('candidate/add/', views.candidate_create, name='candidate_create'),
    path('position/add/', views.position_create, name='position_create'),
    path('meetings/', views.meeting_list, name='meeting_list'),
    path('meeting/add/', views.meeting_create, name='meeting_create'),
    path('recruiters/', views.recruiter_list, name='recruiter_list'),
    path('recruiter/add/', views.recruiter_create, name='recruiter_create'),
    path('meetings/calendar/', views.meeting_calendar, name='meeting_calendar'),
    path('positions/active/', views.active_positions, name='active_positions'),
    path('candidate/<int:pk>/edit/', views.candidate_edit, name='candidate_edit'),
    path('candidate/<int:pk>/delete/', views.candidate_delete, name='candidate_delete'),
    path('recruiting-process/', views.recruiting_process_list, name='recruiting_process_list'),
    path('recruiting-process/add/', views.recruiting_process_create, name='recruiting_process_create'),
    path('recruiting-process/<int:pk>/edit/', views.recruiting_process_edit, name='recruiting_process_edit'),
    path('position/<int:position_id>/recruiting-process/', views.position_recruiting_process, name='position_recruiting_process'),
    path('position/<int:position_id>/overview/', views.position_overview, name='position_overview'),
    path('position/<int:position_id>/candidate/<int:candidate_id>/', 
        views.candidate_recruiting_process, 
        name='candidate_recruiting_process'),
    path('position/<int:position_id>/add-candidate/', 
        views.add_candidate_to_position, 
        name='add_candidate_to_position'),
    path('position/<int:position_id>/process/<int:process_id>/delete/', 
        views.delete_recruiting_process, 
        name='delete_recruiting_process'),
    path('search/competencies/', views.search_competencies, name='search_competencies'),
    path('search/candidates/', views.search_candidates, name='search_candidates'),
    path('search/languages/', views.search_languages, name='search_languages'),
    path('recruiting-process/<int:process_id>/schedule-rejection-email/', 
        views.schedule_rejection_email, 
        name='schedule_rejection_email'),
    path('recruiting-process/<int:process_id>/update-status/', 
        views.update_recruiting_process_status, 
        name='update_recruiting_process_status'),
    path('statistics/', views.recruitment_statistics, name='recruitment_statistics'),
    path('statistics/details/', views.recruitment_statistics_details, name='recruitment_statistics_details'),
    path('candidate/<int:candidate_id>/preview-resume/', views.preview_resume, name='preview_resume'),
    path('parse-cv/', views.parse_cv, name='parse_cv'),
    path('recruiting-process/<int:process_id>/add-comment/', views.add_comment, name='add_comment'),
    path('recruiting-process/<int:process_id>/delete-comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('api/position/<int:position_id>/stage/<str:stage_key>/candidates/', views.stage_candidates_api, name='stage_candidates_api'),
    path('api/clients/create/', views.create_client_api, name='create_client_api'),
    path('api/client/pipeline/save', views.save_pipeline_config, name='save_pipeline_config'),
] 