# Generated by Django 5.1.5 on 2025-02-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('phone_screen', 'Phone Screen'), ('technical', 'Technical Interview'), ('hr', 'HR Interview'), ('client', 'Client Interview'), ('final', 'Final Interview')], max_length=20)),
                ('date_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.recruiter')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
