# Generated by Django 5.1.5 on 2025-02-18 14:28

from django.db import migrations

def migrate_data_forward(apps, schema_editor):
    # Since we've already moved the models, we don't need to migrate data
    pass

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_data_forward, migrate_data_backward),
    ]
